apiVersion: deployments.ff.io/v1alpha1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: deployment-sample
    app.kubernetes.io/part-of: ansible-operator-meetup
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-operator-meetup
  name: deployment-sample
spec:
  size: 2
  reverse_url: "http://run.mocky.io/v3/1d76e782-0d7c-45fa-97f7-bc7b50246524"
