---
- name: nginx conf
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nginx-conf
        namespace: default
      data:
        nginx.conf: |
          events { }

          http {

            server {
              listen 8080;

              location /reverse {
                proxy_pass {{ reverse_url }};
              }
            }
          }

- name: start nginx
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-nginx'
        namespace: default
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: "nginx"
                ports:
                  - containerPort: 8080
                volumeMounts:
                  - mountPath: /etc/nginx
                    readOnly: true
                    name: nginxconf
            volumes:
              - name: nginxconf
                configMap:
                  name: nginx-conf
                  items:
                    - key: nginx.conf
                      path: nginx.conf

- name: expose nginx
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          run: nginx
        name: nginx
        namespace: default
      spec:
        internalTrafficPolicy: Cluster
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
        selector:
          app: nginx
        sessionAffinity: None
        type: ClusterIP


